### ISSUE TITLE
Fix "Make GitHub Release" on TeamCity

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1203]
It currently fails to create a release with `gh` due to auth issues:

```
18:52:00   + pixi run github-release
18:52:00   ✨ Pixi task (default): python utils/github-release.py
18:52:51   HTTP 404: Not Found (https://api.github.com/repos/Deltares/Ribasim/releases
18:52:51   This API operation needs the "repo" scope. To request it, run:  gh auth refresh -h github.com -s repo
18:52:51   Traceback (most recent call last):
18:52:51     File "/opt/teamcityagent/work/d7117c5942be1e0d/utils/github-release.py", line 12, in <module>
18:52:51       subprocess.check_call(
18:52:51     File "/opt/teamcityagent/work/d7117c5942be1e0d/.pixi/envs/default/lib/python3.11/subprocess.py", line 413, in check_call
18:52:51       raise CalledProcessError(retcode, cmd)
18:52:51   subprocess.CalledProcessError: Command '['gh', 'release', 'create', 'v2024.3.0', '--generate-notes', 'ribasim_cli_linux.zip', 'ribasim_cli_windows.zip', 'ribasim_qgis.zip', 'generated_testmodels.zip']' returned non-zero exit status 1.
18:52:51   Currently checked out tag: v2024.3.0
```

https://dpcbuild.deltares.nl/buildConfiguration/Ribasim_Ribasim_MakeGitHubRelease?mode=builds

I worked around it for v2024.3.0 by running the same command locally with the right artifacts downloaded from TeamCity:

```
gh release create v2024.3.0 --generate-notes ribasim_cli_linux.zip ribasim_cli_windows.zip ribasim_qgis.zip generated_testmodels.zip
```

**Comment by Hofer-Julian** [comment]
That is fixed by now
