### ISSUE TITLE
Error when adding the same table twice in QGIS

### ISSUE THREAD

**Issue by deltamarnix** [Deltares/Ribasim#1685]
- Open QGIS and ensure that the Ribasim plugin is installed and enabled.
- Open the application via the Ribasim button on the QGIS toolbar: _Ribasim panel opens_.
- Press the "New" button in the Model tab: _file navigation window pops up_.
- Fill in a name ("test1").
- Press OK: _A toml and database file are created on the given location_.
- Go to the Nodes tab: _All buttons are enabled_.
- Press the Basin / time button: _A layer is added to the layers panel with that name_.
- Press the Basin / time button again: _Error occurs_.

> An error has occurred while executing Python code: 
> 
> ValueError: Name already exists in geopackage: Basin / time 
> Traceback (most recent call last):
>   File "C:\Users\X\Source\Repos\Ribasim\.pixi\qgis_env\profiles\default/python/plugins\ribasim_qgis\widgets\nodes_widget.py", line 61, in new_node_layer
>     node = klass.create(
>            ^^^^^^^^^^^^^
>   File "C:\Users\X\Source\Repos\Ribasim\.pixi\qgis_env\profiles\default/python/plugins\ribasim_qgis\core\nodes.py", line 86, in create
>     raise ValueError(f"Name already exists in geopackage: {cls.input_type()}")
> ValueError: Name already exists in geopackage: Basin / time

Expected: The button gets disabled once a layer with that name was there.

**Comment by Huite** [comment]
Disabling is one option, but it's difficult to implement. I would raise an error here and show a QMessageBox instead.

The reason that it's difficult to implement is because there's all kinds of ways in which people may delete the layer from the underlying geopackage. Through the "Remove from Dataset" button is one, but another is through the Browser Panel. Another is running an SQLite query through QGIS's processing toolbox, or maybe via a script in the background. This means you cannot rely on the Qt signals to inform you that the button should be re-enabled (granted, >99% of deletion would occur through "Remove from Dataset").

What easier to implement is prior to creating the layer, check the layers in the geopackage. Then error message if the name already exists.
To be fair this check already occurs and you could just try-except this specific ValueError and just show this error in a QMessageBox.
