### ISSUE TITLE
Database disk image is malformed

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1973]
Locally I cannot run `pixi run generate-testmodels`. It tends to fail on `basic` or `basic_arrow`. I have no idea why this started happening now. It looks like `self.filepath = filepath` during `model.write` is triggering the reading of the database, which doesn't look desirable.

Sometimes can be reproduced by

```py
import ribasim_testmodels
model = ribasim_testmodels.basic_model()
model.write("d:/temp/model/trivial.toml")
```

```
Pixi task (generate-testmodels in dev): python utils/generate-testmodels.py
Generating allocation_training
Generating allocation_example
Generating backwater
Generating basic_arrow
Generating basic
Traceback (most recent call last):
  File "A:\repo\ribasim\Ribasim\utils\generate-testmodels.py", line 49, in <module>
    model.write(datadir / model_name / "ribasim.toml")
  File "A:\repo\ribasim\Ribasim\python\ribasim\ribasim\model.py", line 307, in write
    self.filepath = filepath
    ^^^^^^^^^^^^^
  File "A:\repo\ribasim\Ribasim\.pixi\envs\dev\Lib\site-packages\pydantic\main.py", line 923, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
  File "A:\repo\ribasim\Ribasim\python\ribasim\ribasim\model.py", line 129, in _ensure_edge_table_is_present
    self.edge.df = self.edge.df.set_geometry("geometry", crs=self.crs)
    ^^^^^^^^^^^^
  File "A:\repo\ribasim\Ribasim\.pixi\envs\dev\Lib\site-packages\pydantic\main.py", line 923, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
  File "A:\repo\ribasim\Ribasim\python\ribasim\ribasim\input_base.py", line 121, in _check_filepath
    data = cls._load(filepath)
           ^^^^^^^^^^^^^^^^^^^
  File "A:\repo\ribasim\Ribasim\python\ribasim\ribasim\input_base.py", line 240, in _load
    ddf = cls._from_db(db, cls.tablename())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\repo\ribasim\Ribasim\python\ribasim\ribasim\input_base.py", line 378, in _from_db
    if exists(connection, table):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\repo\ribasim\Ribasim\python\ribasim\ribasim\db_utils.py", line 15, in exists
    cursor.execute(
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by visr** [comment]
Nevermind, whilst working on an issue I guess I bricked a model database. Removing `generated_testmodels\*` fixed this. Keeping this open to discuss if we want to trigger this code on `self.filepath = filepath`.
